/*
 * Ultrasonic.h
 *
 *  Created on: Oct 18, 2022
 *      Author: Sara
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

void Ultrasonic_edgeProcessing(void);
/*description:
 * This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by
   the ultrasonic sensor.
 */
#define ULTRASONIC_PORT_ID   PORTB_ID
#define ULTRASONIC_PIN_NUM   PIN5_ID

void Ultrasonic_Trigger(void);
/*description:
 * Send the Trigger pulse to the ultrasonic.
 */
uint16 Ultrasonic_readDistance(void);
/*description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
void  Ultrasonic_init(void);
/*description:
 * Initialize the ICU driver as required.
 * Setup the ICU call back function.
 * Setup the direction for the trigger pin as output pin through the
   GPIO driver.
 */

#endif /* ULTRASONIC_H_ */
